--- 
- 
  hosts: tomcat
  name: Tomcat
  tasks: 
    - name: update
      become: true
      apt: 
        cache_valid_time: 3600
        update_cache: true

    - name: install
      become: true
      apt: 
        name: 
          - tomcat9
          - tomcat9-admin
           
